### ISSUE TITLE
Deployment failure in case of version already existed/Signature issue while merging branch

### ISSUE THREAD

**Issue by nitishxp** [einaregilsson/beanstalk-deploy#43]
Hi ,

I am getting the following error even though i have set following use_existing_version_if_available: true
can't we just overwrite the content present in s3?

![image](https://user-images.githubusercontent.com/25002490/93728063-dea53500-fbdb-11ea-9d3f-d23d56917916.png)

**Comment by einaregilsson** [comment]
Hmm. Can you post the full log?

**Comment by nitishxp** [comment]
![Uploading image.png…]()

**Comment by nitishxp** [comment]
![image](https://user-images.githubusercontent.com/25002490/93768188-a8e16a00-fc36-11ea-8aba-619a30ac8d91.png)

**Comment by nitishxp** [comment]
@einaregilsson  I am also getting below error each time when I am Merging a branch the version is being uploaded to s3 but still i get this error

![image](https://user-images.githubusercontent.com/25002490/93838157-4cb62e80-fca6-11ea-8c5f-6f078d82197a.png)

**Comment by einaregilsson** [comment]
Is there anything different in how you create the zip file when you do a merge?

**Comment by nitishxp** [comment]
All is same i just merge the branch and that's it. When i am doing a dummy push it works but in merge it is failing all the time.
The error which i showed above about the version already s3 exists is from this step only by rerunning the same job.

**Comment by nitishxp** [comment]
@einaregilsson any update?

**Comment by einaregilsson** [comment]
Looked at the script. Given the message you're getting it looks like the file already exists in S3, but beanstalk does not have any record of this version existing. The `use_existing_version_if_available` parameter checks if the version exists in Beanstalk, not if the file exists. So I'm wondering how you got into this state, did a previous build for the same version fail?

**Comment by nitishxp** [comment]
Yes the previous build was failed and i re-run the job

**Comment by einaregilsson** [comment]
Ok. I think if a build fails and leaves the beanstalk environment in an inconsistent state (build file exists but build version doesn't in Beanstalk) then the action can't really know what is a reasonable thing to do. Delete the file? Overwrite the file? I think it's a case where a person has to make that call, personally I would not want to create a build with the same version label as an old failed build, which is why I don't use only commit sha's as a version label. Closing this issue.

**Comment by nitishxp** [comment]
Then what to use in version ? what's ur suggestion over it if not sha?

**Comment by einaregilsson** [comment]
Personally I use the variable `GITHUB_RUN_NUMBER` which is just a simple integer that gets incremented with each run of the build.

**Comment by nitishxp** [comment]
So even retrying a failed build will also result in same GITHUB_RUN_NUMBER?

**Comment by dnorth98** [comment]
Just running into this now.  I think this issue should be re-opened.  The problem occurs if

- a run fails (say with an IAM policy error or some other issue)
-  you then re-run the github action jobs

Even using `GITHUB_RUN_NUMBER` will not solve this because as [the docs](https://docs.github.com/en/actions/reference/environment-variables) say

>A unique number for each run of a particular workflow in a repository. This number begins at 1 for the workflow's first run, and increments with each new run. This number does not change if you re-run the workflow run.
